# Use the main Prometheus image.
FROM grafana/grafana
MAINTAINER "er.deepakchandwani@gmail.com"
# Add in the configuration file from the local directory..
#ADD grafana.yaml /etc/prometheus/prometheus.yml
EXPOSE 3000