# Use the main Prometheus image.
FROM prom/prometheus
MAINTAINER "er.deepakchandwani@gmail.com"
# Add in the configuration file from the local directory..
ADD ./prometheus.yaml /etc/prometheus/prometheus.yml
EXPOSE 9090
